version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: entradas_PU
      TZ: UTC
      PGTZ: UTC
